export const typesAction = {
  SUCCESS_GET_NOTE_LIST: "SUCCESS_GET_NOTE_LIST",
  NOTE_FETCH_REQUESTED: "NOTE_FETCH_REQUESTED",
  ERROR_GET_NOTE_LIST: "ERROR_GET_NOTE_LIST",
  ADD_NEW_NOTE: "ADD_NEW_NOTE",
};
